### ISSUE TITLE
Landing page - Step 1

### ISSUE THREAD

**Issue by daljit3** [daljit3/potionfy#1]
Create the basic structure of the landing page by editing index.html and adding the markup.

**Comment by github4maninder** [comment]
@jalad-shrimali, would like to work on this request. assign this to him.

**Comment by jalad-shrimali** [comment]
Hey, @github4maninder I am new to open source and I just saw that this is a 'Good First Issue'. Can you help me and explain to me how I can contribute to this?

**Comment by github4maninder** [comment]
you can fork this repo to your local github profile and then edit the index.html file with the basic  html template some thing like this 
---------
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Potionfy</title>
</head>
<body>
    <H1>Welcome to Potionfy</H1>
</body>
</html>
----------
screenshot attached below with the sample code.

then once is saved create a pull request from your github profile to this main repo.
it will be merged by @daljit3

**Comment by github4maninder** [comment]
![Screen Shot 2022-01-10 at 1 29 24 PM](https://user-images.githubusercontent.com/90073393/148819442-21aae924-7907-451b-892c-20e39c19995a.JPG)
@jalad-shrimali

**Comment by github4maninder** [comment]
its merged with the main repo. looks great 🥇

**Comment by github4maninder** [comment]
this issue is resolved. you can close this issue.

**Comment by daljit3** [comment]
Issue closed.
